# Generated by Django 3.1.2 on 2020-11-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('wordCount', models.CharField(max_length=255, verbose_name='Number of words')),
                ('bookText', models.FileField(upload_to='books/', verbose_name='Book text')),
                ('bookEmotion', models.CharField(max_length=255, verbose_name='Book Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='User Email')),
                ('userId', models.CharField(max_length=255, verbose_name='Spotify user id')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Spotify display name')),
            ],
        ),
    ]
