# Generated by Django 3.1.3 on 2020-11-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_bookemotiongraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.CharField(default=-1, max_length=10, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, upload_to='coverImages/', verbose_name='Cover art'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookEmotionGraph',
            field=models.ImageField(default='bookgraphs/blank.png', upload_to='static/img', verbose_name='Book Bar Graph'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wordCount',
            field=models.CharField(blank=True, max_length=255, verbose_name='Number of words'),
        ),
    ]
