<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-29 18:47
=======
# Generated by Django 3.1.2 on 2020-11-30 00:04
>>>>>>> e44392ec4fe8a15463289d6c6c1e50ed01d55278

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201127_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookRank',
            field=models.CharField(default='0', max_length=10, verbose_name='book rank'),
        ),
    ]
