# Generated by Django 3.1.3 on 2020-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201127_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookRank',
            field=models.CharField(default='0', max_length=10, verbose_name='book rank'),
        ),
    ]
